name: GitHub Actions Demo
run-name: Github Actions EV Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: List all Defaults EV
        run: printenv
      - name: Access Event Name
        run: $GITHUB_EVENT_NAME
